DROP TABLE IF EXISTS tarefa;
DROP TABLE IF EXISTS lista;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE lista (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE tarefa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descricao TEXT NOT NULL,
    completa BOOLEAN DEFAULT FALSE,
    lista_id INT NOT NULL,
    FOREIGN KEY (lista_id) REFERENCES lista(id) ON DELETE CASCADE
);